# Generated by Django 6.0.7 on 2026-07-18 04:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=100)),
                ('stok_tersedia', models.IntegerField(default=0)),
                ('satuan', models.CharField(default='Pcs', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RuangLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruang', models.CharField(max_length=100)),
                ('kapasitas', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('mahasiswa', 'Mahasiswa/PJMK'), ('aslab', 'Asisten Laboratorium'), ('kaleb', 'Kepala Laboratorium')], default='mahasiswa', max_length=20)),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('prodi', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LaporanRekap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laporan', models.CharField(max_length=150)),
                ('konten_rekap', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft Laporan'), ('dikirim', 'Menunggu Review KALAB'), ('revisi', 'Perlu Revisi'), ('approved', 'Approved / Masuk Riwayat')], default='draft', max_length=20)),
                ('ulasan_revisi', models.TextField(blank=True, null=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aslab_pembuat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keperluan', models.TextField()),
                ('nama_dosen', models.CharField(max_length=100)),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField()),
                ('wkt_mulai', models.TimeField()),
                ('wkt_akhir', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi ASLAB'), ('verified', 'Menunggu Persetujuan KALAB'), ('disetujui', 'Disetujui / Jadwal Dikunci'), ('ditolak', 'Ditolak'), ('selesai', 'Selesai / Sudah Dikembalikan')], default='pending', max_length=20)),
                ('tgl_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('catatan_tolak', models.TextField(blank=True, null=True)),
                ('alat_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_auth.alatbahan')),
                ('di_validasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aslab_verifikator', to=settings.AUTH_USER_MODEL)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_mahasiswa', to=settings.AUTH_USER_MODEL)),
                ('ruang_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_auth.ruanglab')),
            ],
        ),
    ]
