# Generated by Django 6.0.6 on 2026-07-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('alat_bahan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_auth.alatbahan')),
                ('peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_alat', to='core_auth.peminjaman')),
            ],
        ),
    ]
